# Generated by Django 4.1.4 on 2023-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_women_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
