# Generated by Django 4.1.4 on 2023-01-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_category_slug_women_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
